travis:
  secure:
    BINSTAR_TOKEN: lFrMMx+YjQIJzvHK9907d0gbYFhXsQxMHmI+/WNdQy4Kodft/toZv3D7UaBrUCttaLJl6RS9DzpHYgMRb7Jertk3qBtg2OOfr8lQqwORgxFcORRWS1Ml34wakk14JkG0AjY4Yp8K14xJvOMdAv3Eu2pa1w4cfLfnOZ8FxbAUwpWwzY7qIyFWE+qIrK0IJQQYw5MsT7Csk/55dz/181i5C+MlB+RPbF+mARBPLkk3Ofvj5aJ3S2P5Csykb2TYHaGdTXqsC2XnKJ0z2rpsLwEwRtIc5xlkjBz7xVtXi2+6H8l7DgUxqyBVgFte5lZlhxcU91fCF2pvauHKGcCCwRoxIsM1H/oh6F5e86FS1JLPWdjAzyEtLkhbqeJfuxmcJQvBStvDXKP6uz6CTWLeKjbTHQXwelDBlYIxDQw08v8AQqI+EJa21KgELf4PblyLJu9AvIOpKPFkI8KKcdvZ3ByCQCSZrbaZxFWxX4wcKSJK5B9eia44twzNn/IS9rkPCT3lbDgn8n7agUvFsf6Hnf7jh8Qq7smYKoL0CvCwkqNPVSn2kN/1eFSAoge3VOSVSRR+7La9XFoifHBEvILhc8UT1roHbGC2uQhm0xqSdEKvcTLT/wZbgaa3V+UafC/OVklF/L5ySKBKmW54ZtcZtCuNqn6yE0erKtP6cRjZ5zgH1sA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
