travis:
  secure:
    BINSTAR_TOKEN: bnp2tx5GtG4VnQzdMntRqQv4B4ho2whGxvOWuKAMjw5Q31nQlp6mCn/HXreprFedvI3JWZsWWxkvKpCeBRhxyw01swYnTro5WOt6EcOEBHA4j001Ro5+JoRTdax5WO2F2xFs6y2rAXdmpusrcTUmPreHLVEIp4+2wfOpUqUcH/oDSHNGg8LnghzkbCJHRYnUYJ2L29MMcgfvYF3qqJvQ/sMqTs+0b8rtPOMt21wkQ5NvYafdZ/3BIc+svbuVBv3SxSUPT1BHrcYuGCgqlUSgZ6dMH3ZaZpapDvgIzielZiCtiKZgFfGo2IGwPC9Y8vEfWg9QKbrH5ME5Coew4cc5EII1vmWkyq8xO67MtZGZKCz5MNE4m+2rfpen+BqwFibP9lo0EDOf1GEpTQcqSPIwBNtDy5CU/b76c6CowlQdox9HHcG/HKFmKVJL/MWbqnzaSWRxiMSN1oWviiXr95ApNAWjXBAYhveBZBkGvYb97b+ELDPVDAhLPStUDCJxa5YBTkqkycy+pl0voIlmyWNqn2oV0H2nFx+YIBEM/s7BDVIJdx5MaMBNBxAv4hMNTvo6tUqnrHkN0GZQCB95t2A2ohpl7I2bU+kjio6YU5JjtjalJXeOv4IAvrcX5JTHCP//+lG7FHRiZ8uwzK9D0QJmfB68kv7eWxXYztkXo+8n0CM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
