travis:
  secure:
    BINSTAR_TOKEN: otxRCl3OwpugV11UuVFJVT5LtP0XFKFPmiIUuwLFAtXRFj2CGf5nMHBjjTtv1i/a3B13PM+xuMubniF+OZl63a1jelM3kur+ZXFX6Gq9HyrvXaEdnFBiEzQt20+parp6QjJsmnBP5zKlAQyPH5zbz0XdA3CrCbpQ6GMuK43GWXIh6Lu5osBz7EeUQ1yQkhO0QvVIDo8Voi3OYaWscvDxrBpwU8jnT6XsG/n9LUFvd2KF8b013Lj4m9LN2MgKLQW0l2TtaVzXqhh8VbjHWshZ6oh/bePkpxr2WCMndHw0tmo2M0fLKXNeG1QuZVJyc7fPHhUHsSnYLUhMvSuXg1+CFnbKa9XCC7m4lozebLV1JLnX7jzc20XtJVC+rRxCX1lnqZyCxhWkzRy4hu6SA9DPf6ot3WUcg0OZ/enka7HIPdJ5yc8IyVNcw608yzQsuqjxi4Jn2ZwqgPqO5ZQ0woWWWNRiYAxioQWfPu4iA7WIN2m3Kbt1ojGdJ1TgDwHJLxgfLjJpMEju649LFbeADOEAUxlH179lKXt8jI6yr8yeiqCn9aa+HNkaGltAVDa6EfJxzqaR4ftmeEJnexwdfe7djfiIlINQ8Xgf5SgHy2fiDzvOcUhlZcL4JN7g34np6BH46wT5i51ZUmISkrSI6m1UY+o1eKuHGOP32/URxJMlR6Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
