travis:
  secure:
    BINSTAR_TOKEN: JKBE4iIllhK5BVu2EQc4kdCut0Q+9yHd2zDLyDJgqSY922GhDOHId9iOqNQZ9MESDgVSw/FHpUGnI7llSMMMzRUPzIOWvwy6Y5ClEY8ZbNuaxZ6UGqRYnk8s66mw1qLWivcgwD6wijNEDNX6loyCIQfss1DK1eBWWsxJGqDwe9RjwecDi/tsE40sEoXH36+cGBz8Rc/hBTsdhxZHOP2SUZfnY3k34JdgSaBbcKOnC99mYWGVcdGt0s/Qq2FtvIgiz3CsPAVyMqBO6btU01hgBdfZxtifhbKctI5CXF3Lg2xMr4Eh1cr4mp2EKihQqo083nrFdX+37JTvEK9vVRC649fN1icwBcW5qYiWoU14TFD4uG5ry8xb0QzES8/0SQuDWQGWMdY21LK8lrwPM+8hXjXAZD5FgMPCAi3v1D2xlk/9j1ab8cVR2/G1ZqVdyM8Qnd5KsTo6yNUsAcnm6+l+etxRO/DD5B6Bl1miNqE/sWrBGxz1f4L0BGkHJpXeUKSeK2Tz3wtaWdIi/gBlaUlcISA7WNA2aOfj3x1SabcdcbrOOz2vmmv8k1aH7CAQrVhVyKg8WRbf/mz5EStdyDQXFkmwHV53VsuPgcw06Z063yNqiWbxYgWTZU1nhN32gFzgtAuEq5BCGn2aw4SNYSjDxV4YrSVwSNJ3dCSlAcTILOU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
