travis:
  secure:
    BINSTAR_TOKEN: KK195ixRCSClITFTpfkO2XhG73gDue5OAOguZc21eX8hHX0O95CO4jQfmh4h/7HfmONFow5jyfgx7sIynSQBc1YcycIHe5dvt1UeCHpUw+o6fLGaA6OckbV7VGDAaCbNX+3a/+Lf2xBtbKfQHUuu1mGFvm9DPi6O/METY6EwX2Qc5B8rbARaT7cI/r0a0ffJ9RAhA8Rs+dkSkzBaBpm97FsNbnYyYn1xYzKDTkAOxbQwdIYf3trXdttord6q1YZRnkFc7sS8PizLn0vYYfY1kQddKWqFYVJ7arQgBD3hxFR/1P40nSmCOOD7t4W5lwz+3AviRslkvdJg6Auk/n23ekg36EGo+r7FRXNRPX3zp1CEmdUxTXJt6iVEgg7UmAjMSdFoCwpHiSyTGg2E8qjx/XDXCrZMChpHfxFvmztQmPL0yGQY/QJiKLKjhGviygVPJIl3ZxSzbBAQdTReDjrXZZeC5fCVdjoSZ38Wcm+FmjotCFPZ6F3cAIXu4FJjRZF9glyySQdrBaFCY7hWuvdDNacwsvhDYwQSaU60oYOZTHIM2m89vyiPy8HHmAXDG8xSXQ/GexkUOfyZv6gsE+RWMcS8dAtDv+6GGM0vnSp1w+sB+EGfYEf7qfHmz0c9qSlNncq+BRmV0v7lmuCr6E+ck4XOMZ41cJvqYCjy5oK8wdg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
